const cfg=window.PORTFOLIO_CONFIG||{};let sb=null;
const loginView=document.getElementById('loginView'),adminView=document.getElementById('adminView');
function readyConfig(){return cfg.SUPABASE_URL&&!cfg.SUPABASE_URL.startsWith('YOUR_')&&cfg.SUPABASE_ANON_KEY&&!cfg.SUPABASE_ANON_KEY.startsWith('YOUR_')}
function val(form,name){return form.elements[name].value.trim()}
async function showAdmin(session){loginView.classList.add('hidden');adminView.classList.remove('hidden');document.getElementById('adminEmail').textContent=session.user.email;await Promise.all([loadProfile(),loadExperience(),loadPublications()])}
async function init(){if(!readyConfig()){document.getElementById('loginMsg').textContent='Supabase is not configured yet. Follow README.md first.';return}sb=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);const {data:{session}}=await sb.auth.getSession();if(session)showAdmin(session)}
document.getElementById('loginForm').addEventListener('submit',async e=>{e.preventDefault();if(!sb)return;const {data,error}=await sb.auth.signInWithPassword({email:document.getElementById('loginEmail').value,password:document.getElementById('loginPassword').value});document.getElementById('loginMsg').textContent=error?error.message:'Signed in';if(data.session)showAdmin(data.session)});
document.getElementById('logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};
document.querySelectorAll('.side-menu button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.side-menu button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tab').forEach(t=>t.classList.add('hidden'));document.getElementById('tab-'+b.dataset.tab).classList.remove('hidden')});
async function loadProfile(){const {data}=await sb.from('profile').select('*').limit(1).maybeSingle();if(!data)return;const f=document.getElementById('profileForm');Object.keys(data).forEach(k=>{if(f.elements[k])f.elements[k].value=data[k]??''})}
document.getElementById('profileForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;const payload={first_name:val(f,'first_name'),last_name:val(f,'last_name'),title:val(f,'title'),degree:val(f,'degree'),short_bio:val(f,'short_bio'),about:val(f,'about'),research:val(f,'research'),email:val(f,'email'),location:val(f,'location'),cv_url:val(f,'cv_url'),updated_at:new Date().toISOString()};const {data:existing}=await sb.from('profile').select('id').limit(1).maybeSingle();const q=existing?sb.from('profile').update(payload).eq('id',existing.id):sb.from('profile').insert(payload);const {error}=await q;document.getElementById('profileMsg').textContent=error?error.message:'Saved successfully.'});
async function loadExperience(){const {data=[]}=await sb.from('experience').select('*').order('sort_order');const box=document.getElementById('experienceAdminList');box.innerHTML='';data.forEach(x=>{const d=document.createElement('div');d.className='list-item';d.innerHTML=`<div><strong>${x.period||''} — ${x.role||''}</strong><br><span class="empty">${x.institution||''}</span></div><div class="row"><button class="btn edit">Edit</button><button class="btn danger del">Delete</button></div>`;d.querySelector('.edit').onclick=()=>fillExp(x);d.querySelector('.del').onclick=()=>deleteExp(x.id);box.appendChild(d)})}
function fillExp(x){const f=document.getElementById('experienceForm');['id','period','role','institution','sort_order'].forEach(k=>f.elements[k].value=x[k]??'')}
async function deleteExp(id){if(!confirm('Delete this item?'))return;await sb.from('experience').delete().eq('id',id);loadExperience()}
document.getElementById('experienceForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,p={period:val(f,'period'),role:val(f,'role'),institution:val(f,'institution'),sort_order:Number(f.elements.sort_order.value||0)};const id=val(f,'id');if(id)await sb.from('experience').update(p).eq('id',id);else await sb.from('experience').insert(p);f.reset();loadExperience()});document.getElementById('expClear').onclick=()=>document.getElementById('experienceForm').reset();
async function loadPublications(){const {data=[]}=await sb.from('publications').select('*').order('year',{ascending:false});const box=document.getElementById('publicationAdminList');box.innerHTML='';data.forEach(x=>{const d=document.createElement('div');d.className='list-item';d.innerHTML=`<div><strong>${x.year||''} — ${x.title||''}</strong><br><span class="empty">${x.venue||''}</span></div><div class="row"><button class="btn edit">Edit</button><button class="btn danger del">Delete</button></div>`;d.querySelector('.edit').onclick=()=>fillPub(x);d.querySelector('.del').onclick=()=>deletePub(x.id);box.appendChild(d)})}
function fillPub(x){const f=document.getElementById('publicationForm');['id','year','title','authors','venue','url'].forEach(k=>f.elements[k].value=x[k]??'');f.elements.published.value=String(!!x.published)}async function deletePub(id){if(!confirm('Delete this publication?'))return;await sb.from('publications').delete().eq('id',id);loadPublications()}
document.getElementById('publicationForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,p={year:val(f,'year'),title:val(f,'title'),authors:val(f,'authors'),venue:val(f,'venue'),url:val(f,'url'),published:f.elements.published.value==='true'};const id=val(f,'id');if(id)await sb.from('publications').update(p).eq('id',id);else await sb.from('publications').insert(p);f.reset();loadPublications()});document.getElementById('pubClear').onclick=()=>document.getElementById('publicationForm').reset();
document.getElementById('uploadForm').addEventListener('submit',async e=>{e.preventDefault();const file=document.getElementById('uploadFile').files[0];if(!file)return;const safe=(Date.now()+'-'+file.name).replace(/[^a-zA-Z0-9._-]/g,'-');const {error}=await sb.storage.from('portfolio').upload(safe,file,{upsert:false});if(error){document.getElementById('uploadMsg').textContent=error.message;return}const {data}=sb.storage.from('portfolio').getPublicUrl(safe);document.getElementById('uploadMsg').innerHTML=`Uploaded. Public URL:<br><input value="${data.publicUrl}" readonly onclick="this.select()">`});
init();
